### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by mmcco** [adulau/ssldump#10]
The [website](http://www.rtfm.com/ssldump/) referenced in the README is 404ing.

Thanks for your time,
Michael

**Comment by adulau** [comment]
The original website has been removed. There is still some information on http://ssldump.sourceforge.net/ . The repository tries to keep all the patches available for ssldump up to date.

**Comment by mmcco** [comment]
Thanks! In that case, it's probably best to remove the URL in the README.

**Comment by adulau** [comment]
Thank you for the proposal. I did a new README.md to clarify this.

https://github.com/adulau/ssldump/blob/master/README.md
