### ISSUE TITLE
configure & make on debian jessie

### ISSUE THREAD

**Issue by ishmaelen** [adulau/ssldump#11]
Hello

Running ./configure yields  _config.status: WARNING:  'Makefile.in' seems to ignore the --datarootdir setting_

There are other errors as well; please see the below URL.
Here is the output from make on [pastebin](http://pastebin.com/HYpLZ8Yt)

ii  openssl                         1.0.1t-1+deb8u5              amd64        Secure Sockets Layer toolkit - cryptographic utility
ii  libpcap-dev                     1.6.2-2                      all          development library for libpcap (transitional package)
ii  libpcap0.8:amd64                1.6.2-2                      amd64        system interface for user-level packet capture
ii  libpcap0.8-dev                  1.6.2-2                      amd64        development library and header files for libpcap0.8

Thanks!

**Comment by qha** [comment]
> Running ./configure yields config.status: WARNING: 'Makefile.in' seems to ignore the --datarootdir setting

This issue is addressed in 2250851d88f465fa88f70d1a0ab9e06aece86170

**Comment by adulau** [comment]
Thanks to @qha - The changes have been merged. I'll close the issue (feel free to reopen if this is is solving the issue).
