### ISSUE TITLE
make And exec error

### ISSUE THREAD

**Issue by Pascal66** [adulau/ssldump#28]
Parrot 2020.2
First the command `make` say ````make: Nothing to be done for 'all'.```` but ````sudo make install```` work.

When launching : 
```
sudo ssldump
ssldump: error while loading shared libraries: libpcap.so.1: cannot open shared object file: No such file or directory
```

But ./configure was fine

**Comment by adulau** [comment]
i cannot reproduce it. Could you reopen the issue if the issue persist with a recent version? Thank you.
