### ISSUE TITLE
release v1.2 could not link openssl 1.1.0

### ISSUE THREAD

**Issue by fwu313** [adulau/ssldump#44]
hello, I find that release v1.2 could not link openssl 1.1.0, could you tell me what version is recommend.

**Comment by wllm-rbnt** [comment]
Hello,

It has been tested on Debian Buster (10.7) with libssl 1.1.1d, and Debian Stretch (9.13) with libssl 1.1.0l.
Can you provide more details about the issue ?


Thanks,

**Comment by adulau** [comment]
This should be fixed. Feel free to reopen the issue if it's not. Thank you.
