### ISSUE TITLE
Add ja3 and ja3s output in ssldump

### ISSUE THREAD

**Issue by adulau** [adulau/ssldump#45]
Add ja3 and ja3s output in ssldump

**Comment by wllm-rbnt** [comment]
Ready for testing --> https://github.com/adulau/ssldump/pull/51/commits/15ad7190fbd2877df82157e60af5fd32da868be0

**Comment by wllm-rbnt** [comment]
Bug fixed in the checksum logic --> https://github.com/adulau/ssldump/pull/51/commits/04deb915a389455a92d7cfc1203d2731dfd8673a
