### ISSUE TITLE
Write the pcap into a fifo file

### ISSUE THREAD

**Issue by michele-deluca** [adulau/ssldump#56]
Hi, into the fork  wllm-rbnt/ssldump was added the possibility to write the pcap into a fifo file (mkfifo test; ssldump -w test).

it is possible to merge this modification into the main branch?

here the link of the modify file.

https://github.com/wllm-rbnt/ssldump/blob/4a6fcb5963538e3d25fc6ab8d57095d6388ef563/pcap/logpkt.c

**Comment by wllm-rbnt** [comment]
Hi,

It was merged a few days ago https://github.com/adulau/ssldump/commit/deb25664963432d5010e5e3f0d22ccb17ce0179f
