### ISSUE TITLE
Write to pcap write the packet without port information

### ISSUE THREAD

**Issue by michele-deluca** [adulau/ssldump#57]
Hi, during the write to pcap (-w options) the packet was printed without the source port and the destination port; either was set to zero:

ssldump -w test.pcap
::::::::::::::::::::::::::::::
tcpdump -r prova.pcap

you can see that the port was setted to zero.

**Comment by michele-deluca** [comment]
Hi in version 1.3 this issue where wasn't. I think is introduced into latest modify.

**Comment by wllm-rbnt** [comment]
@michele-deluca could you please give this PR a try ?
