### ISSUE TITLE
Cannot find libssl in ubuntu 16.04

### ISSUE THREAD

**Issue by licensing-intrax** [adulau/ssldump#78]
error:

`Unable to find libssl on this system
Check 'config.log' for more information

On Debian and Ubuntu systems you can
install the required library and header
files with
  apt install libssl-dev`

`dpkg -l | grep libssl` shows:
`ii  libssl-dev:amd64                      1.0.2g-1ubuntu4.20                              amd64        Secure Sockets Layer toolkit - development files
ii  libssl-doc                            1.0.2g-1ubuntu4.20                              all          Secure Sockets Layer toolkit - development documentation
ii  libssl1.0.0:amd64                     1.0.2g-1ubuntu4.20                              amd64        Secure Sockets Layer toolkit - shared libraries`

Not sure how to proceed. The default ssldump in the repos just coredumps almost as soon as I invoke it.

**Comment by lord8266** [comment]
The current verison of ssldump needs openssl1.1.1, so you have to download/compile that version
