### ISSUE TITLE
circl.lu ssl error

### ISSUE THREAD

**Issue by comotion** [adulau/ssldump#8]
hi,
unsure where else to report this. going to https://circl.lu/services/passive-ssl/ I get a privacy error in chrome because the certificate is for *.circl.lu

**Comment by adulau** [comment]
Hi,

It's https://www.circl.lu/services/passive-ssl/ there is no Subject Alternative Names in the Certificate.

Thank you.

**Comment by comotion** [comment]
Hello. obviously there is no altname, and that is what I consider a bug. If it isn't, maybe the pages shouldn't be served from https://circl.lu

cheers.
